micronaut:
  server:
    port : 5000
    cors:
      enabled: true
  application:
    name: testApi

datasources:
  default:
    driver-class-name: ${DATASOURCE_DEFAULT_DRIVER:org.mariadb.jdbc.Driver}
    db-type: mariadb
    dialect: MYSQL
    jdbc-url: ${DATASOURCE_DEFAULT_URL:`jdbc:mariadb://localhost:3306/pokemon`}
    username: ${DATASOURCE_DEFAULT_USER:example_user}
    password: ${DATASOURCE_DEFAULT_PASSWORD:example_user}
liquibase:
  datasources:
    default:
      change-log: classpath:db/liquibase-changelog.yml
netty:
  default:
    allocator:
      max-order: 3

