name: Micronaut CI/CD Pipeline

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'corretto'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v2
      - name: Give gradle executable permission
        run: chmod +x ./gradlew
      - name: Run gradle build
        run: ./gradlew build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app-jar
          path: build/libs/*-all.jar

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifact
        uses: actions/download-artifact@v3
        with:
          name: app-jar
      - name: List Directory
        run: ls
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ env.AWS_BEANSTALK_APP_NAME }}
          environment_name: ${{ env.AWS_BEANSTALK_APP_ENV }}
          version_label: ${{github.sha}}
          region: ep-south-1
          deployment_package: deploy.zip